In [1]:
import numpy as np
from time import process_time

np_array = np.array([i for i in range(100000000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.07841703399999922


In [ ]:
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
import numpy as np

np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
a = np.array([1,2,3,4])
print(a)
a.shape

[1 2 3 4]


(4,)

In [ ]:
b = np.array([(1,2,3,4),(4,5,6,7)])
print(b)
b.shape

[[1 2 3 4]
 [4 5 6 7]]


(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [ ]:
a = np.zeros((4,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
z = np.full((5,7),2)
print(z)

[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]


In [ ]:
a = np.eye(10)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
b = np.random.random((5,6))
print(b)

[[0.45404139 0.98574579 0.89713069 0.33239339 0.31218188 0.86636705]
 [0.40679336 0.22973619 0.62815118 0.47468284 0.57342545 0.66358565]
 [0.49624738 0.7189827  0.26528367 0.20041515 0.90033352 0.71013218]
 [0.65752972 0.38036886 0.09644952 0.4563816  0.52023175 0.76635682]
 [0.65098263 0.3812821  0.63788106 0.74074622 0.35562697 0.44987617]]


In [ ]:
c = np.random.randint(15,33,(5,2))
print(c)

[[17 17]
 [22 24]
 [23 24]
 [18 22]
 [28 17]]


In [ ]:
import numpy as np
d = np.linspace(10,100,8)
print(d)

[ 10.          22.85714286  35.71428571  48.57142857  61.42857143
  74.28571429  87.14285714 100.        ]


In [ ]:
e = np.arange(10,55,5)
print(e)

[10 15 20 25 30 35 40 45 50]


In [ ]:
my_list = [18,12,6,24,30,36]
np_array = np.asarray(my_list)
print(np_array)
type(np_array)

[18 12  6 24 30 36]


numpy.ndarray

In [ ]:
f = np.random.randint(10,90,(5,5))
print(f)
print(f.shape)
print(f.ndim)
print(f.size)
print(f.dtype)

[[74 61 55 77 72]
 [40 70 12 49 45]
 [20 30 86 63 46]
 [17 48 10 59 44]
 [20 39 53 38 15]]
(5, 5)
2
25
int64


In [ ]:
list1 = [2,4,4,5]
list2 = [5,9,1]
print(list1 + list2)

[2, 4, 4, 5, 5, 9, 1]


In [ ]:
a = np.random.randint(10,30,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)

print(b)

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[17 16 27]
 [24 16 18]
 [24 19 21]]
[[13 19 17]
 [12 18 12]
 [16 11 15]]
[[30 35 44]
 [36 34 30]
 [40 30 36]]
[[ 4 -3 10]
 [12 -2  6]
 [ 8  8  6]]
[[221 304 459]
 [288 288 216]
 [384 209 315]]
[[1.30769231 0.84210526 1.58823529]
 [2.         0.88888889 1.5       ]
 [1.5        1.72727273 1.4       ]]


In [ ]:
a = np.random.randint(5,18,(3,3))
b = np.random.randint(3,28,(3,3))

print("This a matrix :")
print(a)
print()
print("This is b matrix :")
print(b)
print()
print("Add a and b ")
print(np.add(a,b))
print()
print("Subtract a and b")
print(np.subtract(a,b))
print()
print("Multiply a and b")
print(np.multiply(a,b))
print()
print("Division of a and b")
print(np.divide(a,b))

This a matrix :
[[16  8 12]
 [14 15  5]
 [17  7  9]]

This is b matrix :
[[18  3 26]
 [25  6  8]
 [16 18 25]]

Add a and b 
[[34 11 38]
 [39 21 13]
 [33 25 34]]

Subtract a and b
[[ -2   5 -14]
 [-11   9  -3]
 [  1 -11 -16]]

Multiply a and b
[[288  24 312]
 [350  90  40]
 [272 126 225]]

Division of a and b
[[0.88888889 2.66666667 0.46153846]
 [0.56       2.5        0.625     ]
 [1.0625     0.38888889 0.36      ]]


In [ ]:
my_array = np.random.randint(0,10,(2,3))
print(my_array)
#print(my_array.shape)

print()

print("Now i will print the transpose of my array")

d = np.transpose(my_array)
print(d)

[[1 6 5]
 [4 6 4]]

Now i will print the transpose of my array
[[1 4]
 [6 6]
 [5 4]]


In [ ]:
my_array = np.random.randint(0,10,(2,5))
print(my_array)
print("The shape of the array : ", my_array.shape)

print()
print("Now i will print the transpose of the array : ")
trans2 = my_array.T
print(trans2)
print("The shape of the array : ", trans2.shape)

[[7 9 2 8 4]
 [1 8 4 6 6]]
The shape of the array :  (2, 5)

Now i will print the transpose of the array : 
[[7 1]
 [9 8]
 [2 4]
 [8 6]
 [4 6]]
The shape of the array :  (5, 2)


In [ ]:
a = np.random.randint(0,10,(3,6))
print(a)
print()
print(a.shape)

b = a.reshape(2,9)
print(b)
print()
print(b.shape)

[[4 3 3 4 5 2]
 [9 7 9 8 6 4]
 [6 3 7 4 0 4]]

(3, 6)
[[4 3 3 4 5 2 9 7 9]
 [8 6 4 6 3 7 4 0 4]]

(2, 9)
