**YouTube Tutorial**


[here the link](https://youtu.be/r1bquDz5GGA?si=PxNiqwKkdo-4CLst)

**Document**

[Click Here](https://github.com/The-Pocket/PocketFlow-Tutorial-Video-Generator/blob/main/docs/llm/pytorch.md)

In [ ]:
import torch
data = [[1,2,3],[4,5,6]]
myTensor = torch.tensor(data)
myTensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
shape = (2,3)
random_tensor = torch.rand(shape)
random_tensor

tensor([[0.1370, 0.5831, 0.2527],
        [0.2629, 0.1928, 0.0303]])

In [ ]:
ones = torch.ones(shape)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
zeros = torch.zeros(shape)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
mimic_tensor = torch.rand_like(myTensor,dtype=float)
mimic_tensor

tensor([[0.3863, 0.1597, 0.4418],
        [0.3896, 0.0030, 0.2820]], dtype=torch.float64)

In [ ]:
print(myTensor.shape)
print(myTensor.dtype)
print(myTensor.device)

torch.Size([2, 3])
torch.int64
cpu


In [ ]:
w = torch.tensor([[1.0,9.0],[2.0,6.0]],requires_grad= True)
print(w.requires_grad)

True


In [ ]:
myTensor.requires_grad

False

In [ ]:
a = torch.tensor(2.0,requires_grad=True)
b = torch.tensor(1.0,requires_grad=True)
x = torch.tensor(3.0,requires_grad=True)
y = a + b
z = y*a

In [ ]:
z.grad_fn

In [ ]:
y.grad_fn

In [ ]:
print(a.grad_fn)

None


In [ ]:
a = torch.tensor([[1.0,2.0],[3.0,4.0]])
b = torch.tensor([[5.0,6.0],[7.0,8.0]])
a*b

tensor([[ 5., 12.],
        [21., 32.]])

In [ ]:
 # shape = (2,3)
 a = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
 # shape = (3,2)
 b = torch.tensor([[7.0,8.0],[9.0,10.0],[11.0,12.0]])
 # shape = (2,2)
 a @ b  # matrix multiplication

tensor([[ 58.,  64.],
        [139., 154.]])

In [ ]:
a = torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])


over_all_average = torch.mean(a)
over_all_average

tensor(3.5000)

In [ ]:
torch.mean(a,dim=0)

tensor([2.5000, 3.5000, 4.5000])

In [ ]:
torch.mean(a,dim = 1)

tensor([2., 5.])

In [ ]:
x = torch.arange(12).reshape(3,4)
x[:,2]

tensor([ 2,  6, 10])

In [ ]:
x[:,2]

tensor([ 2,  6, 10])

In [ ]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
import torch
scores = torch.tensor([[12.0,3.0,21.0],[28.0,3.5,5.3]])

scores.argmax(dim=1)

tensor([2, 0])

In [ ]:
scores.argmax(dim=0)

tensor([1, 1, 0])

In [ ]:
data = torch.tensor([
    [1.0,2.0,3.0],
    [4.0,5.0,6.0],
    [7.0,8.0,9.0]
])

selected_indices = torch.tensor([[2],[0],[1]])
torch.gather(data,dim=1,index=selected_indices)

tensor([[3.],
        [4.],
        [8.]])

In [ ]:
N = 10

D_in = 1
D_out = 1

x = torch.randn(N,D_in)

true_W = torch.tensor([[2.0]])
true_B = torch.tensor([1.0])

y_true = x @ true_W + true_B + torch.randn(N,D_out)*0.1

In [ ]:
w = torch.randn(D_in,D_out,requires_grad=True)
b = torch.randn(1,D_out,requires_grad=True)

print(w)
print(b)

tensor([[0.6441]], requires_grad=True)
tensor([[-0.1619]], requires_grad=True)


In [ ]:
y_pred = x @ w + b

In [ ]:
print(y_pred)

tensor([[-1.3824],
        [ 0.6553],
        [-0.2539],
        [-0.0330],
        [ 0.1758],
        [ 0.7989],
        [-0.1842],
        [-0.3263],
        [-0.1256],
        [ 0.2337]], grad_fn=<AddBackward0>)


In [ ]:
print(y_true)

tensor([[-2.9051],
        [ 3.5422],
        [ 0.6982],
        [ 1.2516],
        [ 1.9689],
        [ 4.0835],
        [ 0.9498],
        [ 0.2799],
        [ 1.0794],
        [ 2.0920]])


In [ ]:
error = y_true - y_pred
mean_squared_error = torch.mean(error**2)
print(mean_squared_error)

tensor(3.3772, grad_fn=<MeanBackward0>)


In [ ]:
mean_squared_error.backward()

In [ ]:
print(w.grad)
print(b.grad)

tensor([[-2.7050]])
tensor([[-2.6964]])


In [ ]:
learning_rate,epoch = 0.1,100

w = torch.randn(D_in,D_out,requires_grad=True)
b = torch.randn(1,D_out,requires_grad=True)

for i in range(epoch):
  y_hat = x @ w + b
  error = y_true - y_hat
  mean_squared_error = torch.mean(error**2)
  mean_squared_error.backward()

  with torch.no_grad():
    w -= learning_rate*w.grad
    b -= learning_rate*b.grad
    w.grad.zero_()
    b.grad.zero_()

In [ ]:
print(w)

tensor([[2.0489]], requires_grad=True)


In [ ]:
print(true_W)

tensor([[2.]])


In [ ]:
D_in = 1 #input features
D_out = 1 #output features

linear_layer = torch.nn.Linear(in_features = D_in,out_features = D_out)# 1 input features and 1 output features

print(linear_layer.weight)
print(linear_layer.bias)

y_hat_nn = linear_layer(x)
print(y_hat_nn)

Parameter containing:
tensor([[0.8886]], requires_grad=True)
Parameter containing:
tensor([-0.3777], requires_grad=True)
tensor([[-2.0615],
        [ 0.7498],
        [-0.5046],
        [-0.1998],
        [ 0.0882],
        [ 0.9478],
        [-0.4085],
        [-0.6044],
        [-0.3275],
        [ 0.1682]], grad_fn=<AddmmBackward0>)


In [ ]:
sample_data = torch.tensor([[1.0],[-3.0],[5.0],[-.06],[5.5]])

relu = torch.nn.ReLU()
relu_data = relu(sample_data)

print(f'My sample data {sample_data}')
print(f'My relu data {relu_data}')

My sample data tensor([[ 1.0000],
        [-3.0000],
        [ 5.0000],
        [-0.0600],
        [ 5.5000]])
My relu data tensor([[1.0000],
        [0.0000],
        [5.0000],
        [0.0000],
        [5.5000]])


In [ ]:
import torch
vocab_size = 10 # our language have 10 words
emmbeding_dim = 3 # represent each word by a 3D vector

embedding_layer = torch.nn.Embedding(num_embeddings=vocab_size,embedding_dim=emmbeding_dim)

inputs_id = torch.tensor([1,5,0,8]) # lets imagine a sentence with each word as an ID's

word_vector = embedding_layer(inputs_id)
print(word_vector)

tensor([[-1.4445,  0.8725,  0.5782],
        [-0.3599,  0.9515,  0.2820],
        [-0.3531,  0.0063,  0.4157],
        [-0.1996,  0.8093, -0.5365]], grad_fn=<EmbeddingBackward0>)


In [ ]:
test_sentence = torch.tensor([5,0,0,1,4])
new_vector = embedding_layer(test_sentence)
print(new_vector)

tensor([[-0.3599,  0.9515,  0.2820],
        [-0.3531,  0.0063,  0.4157],
        [-0.3531,  0.0063,  0.4157],
        [-1.4445,  0.8725,  0.5782],
        [ 0.3906,  0.5339,  0.5298]], grad_fn=<EmbeddingBackward0>)


In [ ]:
norm_layer = torch.nn.LayerNorm(normalized_shape=3)

input_features = torch.tensor([[1.0,2.0,3.0],[4.0,6.0,9.0],[1.0,-13.0,6.0]])

normalized_features = norm_layer(input_features)

normalized_features

tensor([[-1.2247,  0.0000,  1.2247],
        [-1.1355, -0.1622,  1.2978],
        [ 0.3731, -1.3679,  0.9948]], grad_fn=<NativeLayerNormBackward0>)

In [ ]:
normalized_features.mean(dim=1).round(decimals=2)

tensor([0., -0., -0.], grad_fn=<RoundBackward1>)

In [ ]:
normalized_features.std()

tensor(1.0607, grad_fn=<StdBackward0>)

In [ ]:
dropout_layer = torch.nn.Dropout(p=0.5)

input_features = torch.ones(1,10)

# training
output_features = dropout_layer(input_features)
output_features

tensor([[0., 0., 2., 0., 2., 2., 2., 0., 2., 2.]])

In [ ]:
# evalution
dropout_layer.eval()
output_features = dropout_layer(input_features)
output_features

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
import torch.nn as nn

class LinearRegression(nn.Module):
  def __init__(self, in_features,out_features):
    super().__init__()

    self.linear_layer = nn.Linear(in_features=in_features,out_features=out_features)

  def forward(self,x):
    return self.linear_layer(x)

model = LinearRegression(in_features=1,out_features=1)

In [ ]:
print(model)

LinearRegression(
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)


In [ ]:
import torch.optim as optim

learning_rate = 0.1

optimizer = optim.Adam(params=model.parameters(),lr=learning_rate)

loss_fn = nn.MSELoss()

In [ ]:
epoch = 101

for i in range(epoch):
  #forward pass
  y_hat = model(x)

  # loss calculation
  loss = loss_fn(y_hat,y_true)

  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  if(i%10==0):
    print(f'Epoch {i:02d}: Loss = {loss.item():.4f}')

Epoch 00: Loss = 1.2134
Epoch 10: Loss = 0.0617
Epoch 20: Loss = 0.0489
Epoch 30: Loss = 0.0300
Epoch 40: Loss = 0.0092
Epoch 50: Loss = 0.0072
Epoch 60: Loss = 0.0075
Epoch 70: Loss = 0.0062
Epoch 80: Loss = 0.0060
Epoch 90: Loss = 0.0060
Epoch 100: Loss = 0.0060


In [ ]:
import torch.nn as nn

class FeedForward(nn.Module):
  def __init__(self,emmbeding_dim,ffn_dim):
    super().__init__()
    self.layer1 = nn.Linear(emmbeding_dim,ffn_dim)
    self.activation = nn.GELU()
    self.layer2 = nn.Linear(ffn_dim,emmbeding_dim)

  def forward(self,x):
    x = self.layer1(x)
    x = self.activation(x)
    x = self.layer2(x)
    return x

**Lets jump to Transformer**

